#server:
#  port: 8081

spring:
  application:
    name: redmeter-spring-example

  redis:
    host: localhost
#    port:

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: info