{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "耗时 P99",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(command, le) (rate(redisson_redis_command_timer_seconds_bucket[$__rate_interval]))) * 1000",
     "legendFormat": "P99 {{command}}"
    }
   ]
  },
  {
   "title": "耗时 P90",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(command, le) (rate(redisson_redis_command_timer_seconds_bucket[$__rate_interval]))) * 1000",
     "legendFormat": "P90 {{command}}"
    }
   ]
  },
  {
   "title": "连接池",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by(node) (redisson_redis_connections_idle)",
     "legendFormat": "Idle"
    },
    {
     "expr": "redisson_redis_connections_active",
     "legendFormat": "Active"
    },
    {
     "expr": "redisson_redis_connections_total",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "耗时 P50",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(command, le) (rate(redisson_redis_command_timer_seconds_bucket[$__rate_interval]))) * 1000",
     "legendFormat": "P50 {{command}}"
    }
   ]
  },
  {
   "title": "最长耗时",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "topk(5, redisson_redis_command_timer_seconds) * 1000",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "命令数",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "rate(redisson_redis_command_counter_total[$__rate_interval])",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "数据接收速率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "rate(redisson_redis_command_size_bytes_sum{type=\"receive\"}[$__rate_interval]) / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "数据发送速率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "rate(redisson_redis_command_size_bytes_sum{type=\"send\"}[$__rate_interval]) / 1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}